title: carstenj
subtitle: software, matematik og data
baseurl: ""
url: "https://carsten-j.github.io"
repository: "carsten-j/carsten-j.github.io"

date_format: "%Y-%m-%d"

encoding:     "utf-8"

# Other
permalink: /:year/:month/:day/:title.html
timezone: Europe/Copenhagen

show_drafts: false

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed

# Be sure to exclude vendor from your _config.yml
# Travis bundles all gems in the vendor directory on its build servers,
# which Jekyll will mistakenly read and explode on.
exclude: [vendor, Gemfile, Gemfile.lock]
